chore: fix anti-tamper again;

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,13 +9,12 @@ jobs:
       - uses: actions/checkout@v2
       - run: yarn bootstrap
       - run: yarn build
-      - name: Anti-tamper Check
+      - name: Anti-tamper check
         run: '[[ "$(git diff-files)" != "" ]] && echo
           "---------------------------------------------------------------------------------"
-          && echo "ERROR: files modified during build (anti-tamper)" && echo
-          "Please make sure to build locally and commit any changed files." &&
-          echo
+          && echo "ERROR: files modified during build" && echo "Please make sure
+          to build locally and commit any changes" && echo
           "---------------------------------------------------------------------------------"
-          && git diff && exit 1'
+          && git diff-files && git diff && exit 1'
     container:
       image: jsii/superchain
