another try

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,11 +10,12 @@ jobs:
       - run: yarn bootstrap
       - run: yarn build
       - name: Anti-tamper check
-        run: '[[ "$(git diff-files)" != "" ]] && echo
-          "---------------------------------------------------------------------------------"
-          && echo "ERROR: files modified during build" && echo "Please make sure
-          to build locally and commit any changes" && echo
-          "---------------------------------------------------------------------------------"
-          && git diff-files && git diff && exit 1'
+        run: "[[ \"$(git status --porcelain=v1 | grep -v '^?? ')\" != \"\" ]] && echo
+          \"-------------------------------------------------------------------\
+          --------------\" && echo \"ERROR: files modified during build\" &&
+          echo \"Please make sure to build locally and commit any changes\" &&
+          echo
+          \"-------------------------------------------------------------------\
+          --------------\" && git diff && exit 1"
     container:
       image: jsii/superchain
