refactor

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,71 +5,6 @@ on:
   pull_request: {}
   workflow_dispatch: {}
 jobs:
-  build:
-    runs-on: ${{ matrix.runner.os }}
-    permissions:
-      contents: write
-    outputs:
-      self_mutation_happened: ${{ steps.self_mutation.outputs.self_mutation_happened }}
-    env:
-      CI: "true"
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event.pull_request.head.ref }}
-          repository: ${{ github.event.pull_request.head.repo.full_name }}
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18.14.2
-      - name: Install dependencies
-        run: yarn install --check-files
-      - name: build
-        run: node ./projen.js build
-        continue-on-error: ${{ matrix.runner.experimental }}
-      - name: Upload coverage to Codecov
-        uses: codecov/codecov-action@v3
-        with:
-          directory: coverage
-        if: ${{ !matrix.runner.experimental }}
-      - name: Find mutations
-        id: self_mutation
-        run: |-
-          git add .
-          git diff --staged --patch --exit-code > .repo.patch || echo "self_mutation_happened=true" >> $GITHUB_OUTPUT
-        working-directory: ./
-      - name: Upload patch
-        if: ${{ steps.self_mutation.outputs.self_mutation_happened && !matrix.runner.experimental }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: .repo.patch
-          path: .repo.patch
-          overwrite: true
-      - name: Fail build on mutation
-        if: steps.self_mutation.outputs.self_mutation_happened
-        run: |-
-          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
-          cat .repo.patch
-          exit 1
-      - name: Backup artifact permissions
-        run: cd dist && getfacl -R . > permissions-backup.acl
-        continue-on-error: true
-        if: ${{ !matrix.runner.experimental }}
-      - name: Upload artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: build-artifact
-          path: dist
-          overwrite: true
-        if: ${{ !matrix.runner.experimental }}
-    strategy:
-      matrix:
-        runner:
-          - os: ubuntu-latest
-            experimental: false
-          - os: windows-latest
-            experimental: true
   self-mutation:
     needs: build
     runs-on: ubuntu-latest
@@ -240,3 +175,77 @@ jobs:
       - name: Install dependencies
         run: yarn install --check-files --frozen-lockfile
       - run: node ./projen.js integ
+  build_matrix:
+    runs-on: ${{ matrix.runner.os }}
+    permissions:
+      contents: write
+    outputs:
+      self_mutation_happened: ${{ steps.self_mutation.outputs.self_mutation_happened }}
+    env:
+      CI: "true"
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.ref }}
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 18.14.2
+      - name: Install dependencies
+        run: yarn install --check-files
+      - name: build
+        run: node ./projen.js build
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v3
+        with:
+          directory: coverage
+        if: ${{ !matrix.runner.experimental }}
+      - name: Find mutations
+        id: self_mutation
+        run: |-
+          git add .
+          git diff --staged --patch --exit-code > .repo.patch || echo "self_mutation_happened=true" >> $GITHUB_OUTPUT
+        working-directory: ./
+      - name: Upload patch
+        if: ${{ steps.self_mutation.outputs.self_mutation_happened && !matrix.runner.experimental }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: .repo.patch
+          path: .repo.patch
+          overwrite: true
+      - name: Fail build on mutation
+        if: steps.self_mutation.outputs.self_mutation_happened
+        run: |-
+          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
+          cat .repo.patch
+          exit 1
+      - name: Backup artifact permissions
+        run: cd dist && getfacl -R . > permissions-backup.acl
+        continue-on-error: true
+        if: ${{ !matrix.runner.experimental }}
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: build-artifact
+          path: dist
+          overwrite: true
+        if: ${{ !matrix.runner.experimental }}
+    strategy:
+      matrix:
+        runner:
+          - os: ubuntu-latest
+            experimental: false
+          - os: windows-latest
+            experimental: true
+    continue-on-error: ${{ matrix.runner.experimental }}
+  build:
+    runs-on: ubuntu-latest
+    needs:
+      - build_matrix
+    outputs:
+      self_mutation_happened: ${{ needs.build_matrix.outputs.self_mutation_happened }}
+    steps:
+      - name: OK
+        run: echo "OK"
