chore: fix anti-tamper workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,6 +10,12 @@ jobs:
       - run: yarn bootstrap
       - run: yarn build
       - name: anti-tamper
-        run: '[[ "$(git diff-files)" == "" ]]'
+        run: '[[ "$(git diff-files)" != "" ]] && echo
+          "---------------------------------------------------------------------------------"
+          && echo "ERROR: files modified during build (anti-tamper)" && echo
+          "Please make sure to build locally and commit any changed files." &&
+          echo
+          "---------------------------------------------------------------------------------"
+          && git diff && exit 1'
     container:
       image: jsii/superchain
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -12,7 +12,13 @@ jobs:
       - run: yarn bootstrap
       - run: yarn build
       - name: anti-tamper
-        run: '[[ "$(git diff-files)" != "" ]] && echo "ERROR: files modified during build (anti-tamper). Please make sure to build locally and commit any changed files" && git diff && exit 1'
+        run: '[[ "$(git diff-files)" != "" ]] && echo
+          "---------------------------------------------------------------------------------"
+          && echo "ERROR: files modified during build (anti-tamper)" && echo
+          "Please make sure to build locally and commit any changed files." &&
+          echo
+          "---------------------------------------------------------------------------------"
+          && git diff && exit 1'
       - name: Upload artifact
         uses: actions/upload-artifact@v1
         with:
