chore: self mutation

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -37,42 +37,22 @@ jobs:
           git add .
 
           git diff --staged --patch --exit-code > .repo.patch || echo "::set-output name=self_mutation_happened::true"
-      - if: ${{ steps.self_mutation.outputs.self_mutation_happened }}
+      - if: steps.self_mutation.outputs.self_mutation_happened
         name: Upload patch
         uses: actions/upload-artifact@v2
         with:
           name: .repo.patch
           path: .repo.patch
       - name: Fail build on mutation
-        if: ${{ steps.self_mutation.outputs.self_mutation_happened }}
-        run: exit 1
+        if: steps.self_mutation.outputs.self_mutation_happened
+        run: |-
+          echo "::error::Mutation detected, please update your branch."
+          exit 1
       - name: Upload artifact
         uses: actions/upload-artifact@v2.1.1
         with:
           name: build-artifact
           path: dist
-  anti-tamper:
-    needs: build
-    runs-on: ubuntu-latest
-    permissions: {}
-    if: always() && needs.build.outputs.self_mutation_happened &&
-      github.event.pull_request.head.repo.full_name != github.repository
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-        with:
-          ref: ${{ github.event.pull_request.head.ref }}
-          repository: ${{ github.event.pull_request.head.repo.full_name }}
-      - name: Download patch
-        uses: actions/download-artifact@v2
-        with:
-          name: .repo.patch
-          path: ${{ runner.temp }}
-      - name: Apply patch
-        run: '[ -s ${{ runner.temp }}/.repo.patch ] && git apply ${{ runner.temp
-          }}/.repo.patch || echo "Empty patch. Skipping."'
-      - name: Found diff after build (update your branch)
-        run: git add . && diff --staged --exit-code
   self-mutation:
     needs: build
     runs-on: ubuntu-latest
