Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -12,7 +12,7 @@ jobs:
       - run: yarn bootstrap
       - run: yarn build
       - name: anti-tamper
-        run: '[[ "$(git diff-files)" == "" ]]'
+        run: '[[ "$(git diff-files)" != "" ]] && echo "ERROR: files modified during build (anti-tamper). Please make sure to build locally and commit any changed files" && git diff && exit 1'
       - name: Upload artifact
         uses: actions/upload-artifact@v1
         with:
